### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by acaudle** [geerlingguy/ansible-role-jenkins#127]
TASK [geerlingguy.jenkins : Wait for Jenkins to start up before proceeding.] ***
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ok: []
[WARNING]: Consider using get_url or uri module rather than running curl

TASK [geerlingguy.jenkins : Get the jenkins-cli jarfile from the Jenkins server.] ***
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ok: []

**Comment by geerlingguy** [comment]
@acaudle - Sorry to close this quickly, but basically I purposely am keeping `always_run` until Ansible 2.3 is released. Ansible 2.2 introduced the new `check_mode` module, and I don't want to break compatibility with everyone using Ansible 2.0 and 2.1 just because there's a new variable... so I'm waiting to make the change so people have more time to upgrade.
