### ISSUE TITLE
Please reopen #132

### ISSUE THREAD

**Issue by jliscom-Slalom** [geerlingguy/ansible-role-jenkins#133]
Please reopen #132 None of the fixes mentioned do anything

**Comment by geerlingguy** [comment]
@jliscom-Slalom - I'd rather not reopen an old issue, but rather make a new issue for what could potentially be a new problem you're encountering.

That other issue was definitely caused by an insufficient Java version; I wonder if your issue may be something else entirely (I have been testing this role extensively this week on Ubuntu 16.04, but haven't touched CentOS for a few weeks, so maybe there's some new bug specific to CentOS?

In any case, can you please create a new issue, and describe how you're using the role and how it's not working, with relevant logs / error messages (and ideally, steps to reproduce)?
