### ISSUE TITLE
Not starting on Centos 7

### ISSUE THREAD

**Issue by markgargan** [geerlingguy/ansible-role-jenkins#143]
hi there,

Great resource, thanks very much for putting it together. I've installed the role in Centos 7 however Jenkins won't start and even fails to start silently. 

I put some echo statements the /etc/rc.d/init.d/jenkins script and it appears to fail or at least fall silent after executing the 
/etc/init.d/functions
script. 
It appears to be using the daemon function but that's not till further down the script. Does the /etc/init.d/functions script redirect all the subsequent process output regardless? If so any ideas where I could find it to see what's happening? 

Also I had to update a number of the task steps to run as root? Is this because the role doesn't necessarily support Centos or would it be because I need to use the root user in ansible hosts to execute the role?

Thanks,
Mark.

**Comment by markgargan** [comment]
Just in case, I'm on a Windows host in work and a Mac host at home and encountered the same issue.

**Comment by markgargan** [comment]
Hi there, it turned out to be a disparity between the latest version of Jenkins requiring Java 8 and the default install being 1.7 

I see that it's almost the first thing you mention in the requirements section so it shouldn't have taken me quite so long to twigg it. Would it be worth considering updating the default out of the box installation so that it uses java 8? Or perhaps some warning if the version of jenkins is greater than 2.54 and the jdk being installed is less than 8? 

Thanks,
Mark.

**Comment by geerlingguy** [comment]
> Would it be worth considering updating the default out of the box installation so that it uses java 8?

I don't want to have the responsibility of managing Java installations in this role—I already have the `geerlingguy.java` role for that, and it has documentation for how to switch between versions in most cases.

> Or perhaps some warning if the version of jenkins is greater than 2.54 and the jdk being installed is less than 8?

This might be doable... but it's a situation where I could hardcode something about requiring Java 8... then a year from now Java 9 comes out and we run into the same issue, and then I have a bunch of conditionals that make this role harder to maintain (since I usually support my roles on 3-5 OS distros, and all of them at least on the latest OS and usually n-1 too).

I think the warning in the README, and the errors that are apparent once you glance in the logs, should hopefully be adequate for now. Also, people will google the error and get to this issue, so thank you for documenting it :)
