### ISSUE TITLE
Pinning a version breaks replaying

### ISSUE THREAD

**Issue by mkesper** [geerlingguy/ansible-role-jenkins#218]
Pinning to a special version fails if the playbook is rerun:

```
TASK [geerlingguy.jenkins : Install our specific version of Jenkins.] **********
fatal: [secs-test1-buildjenkins-1a.euc1.securesystem.net]: FAILED! => {"changed": false, "msg": "A later version is already installed"}
	to retry, use: --limit @/var/lib/jenkins/workspace/BUILD_test1-secsys_p_buildjenkins/playbook.retry
```

**Comment by mkesper** [comment]
From a logical point of view, the apt / yum repos should be removed if an installation requests a specific version from a fixed URL.

**Comment by timblaktu** [comment]
I'm getting this error when trying to "downgrade" my Jenkins master instance by specifying an older release and rerunning the playbook that uses this role. Is downgrading Jenkins version not supported in this role?

Specifically, I am downgrading to 2.191, in order to work around the problems with installing plugins when CSRF protection is on.

**Comment by albertski** [comment]
I am running into issue with the latest version of Jenkins and would like to downgrade but when I input a `jenkins_version` I get the following `A later version is already installed`.  @timblaktu @mkesper were you able to downgrade somehow?

**Comment by albertski** [comment]
I was able to downgrade manually by replacing the jenkins.war.

**Comment by mkesper** [comment]
Sorry, I didn't try for a long time any more.

**Comment by timblaktu** [comment]
I'm getting this again today. This is on a Debian 10 machine - I can ssh in and see that jenkins package version 2.270 is installed:

```
ansible@jenkins-testing:~$ sudo apt show jenkins
Package: jenkins
Version: 2.270
.
.
```

Which I suppose explains why I'm getting this error - My invocation of this role tells it `jenkins_version: 2.222.3`.

Probably this is happening bc something on my system has upgraded the jenkins package (along with all packages) to the latest version provided by Debian Buster repos.

I see [here](https://github.com/geerlingguy/ansible-role-jenkins/blob/764c049941c98f76726cda02a076914a1f1b5fb7/tasks/setup-Debian.yml) where it's basically just downloading a versioned .deb from jenkins' download site. I.e. it's not using apt to manage the packages.

So, I supposed the only thing to do was to purge the installed (upgraded) jenkins package, and retry the role. This installed 2.222.3 again, but then the jenkins service failed to start:

```
ansible@jenkins-testing:~$ sudo apt list --installed | grep jenkins
jenkins/now 2.222.3 all [installed,upgradable to: 2.270]

ansible@jenkins-testing:~$ sudo service jenkins status
● jenkins.service - LSB: Start Jenkins at boot time
   Loaded: loaded (/etc/init.d/jenkins; generated)
   Active: failed (Result: exit-code) since Mon 2020-12-14 15:40:13 PST; 5
     Docs: man:systemd-sysv-generator(8)
  Process: 2393 ExecStart=/etc/init.d/jenkins start (code=exited, status=1

Dec 14 15:40:13 jenkins-testing systemd[1]: Starting LSB: Start Jenkins at
Dec 14 15:40:13 jenkins-testing jenkins[2393]: Found an incorrect Java ver
Dec 14 15:40:13 jenkins-testing jenkins[2393]: Java version found:
Dec 14 15:40:13 jenkins-testing jenkins[2393]: openjdk version "11.0.9.1"
Dec 14 15:40:13 jenkins-testing jenkins[2393]: OpenJDK Runtime Environment
Dec 14 15:40:13 jenkins-testing jenkins[2393]: OpenJDK 64-Bit Server VM (b
Dec 14 15:40:13 jenkins-testing jenkins[2393]: Aborting
Dec 14 15:40:13 jenkins-testing systemd[1]: jenkins.service: Control proce
Dec 14 15:40:13 jenkins-testing systemd[1]: jenkins.service: Failed with r
Dec 14 15:40:13 jenkins-testing systemd[1]: Failed to start LSB: Start Jen
```

Anyone know why this error is happening?

**Comment by timblaktu** [comment]
So, in SUMMARY:

1. Any manual upgrades of jenkins package on the target system will break this role, which performs no version checking - it just downloads a versioned .deb and installs it with the apt module. This breaks when there is a newer version installed. It would seem this could be fixed by changing [the debian setup tasks](https://github.com/geerlingguy/ansible-role-jenkins/blob/764c049941c98f76726cda02a076914a1f1b5fb7/tasks/setup-Debian.yml#L35) to check the version installed, and purge it if different than the one specified, before installing the downloaded .deb.

2. If you ever encounter "Found an incorrect Java version" in the jenkins service log when running this role, check out [this fix](https://github.com/jenkinsci/packaging/pull/198), which has been merged into master but as of today has not yet been released. For ansible-provisioned jenkinses, fixing this manually is an ok workaround, since this role will do nothing if the jenkins package is already installed.

**Comment by timblaktu** [comment]
I have recreated my jenkins cluster from the ground up and provisioned them with the same playbook that caused the above problems, and lo and behold the issue persists. I.e. on a fresh install of jenkins on Debian 10 using this role (specifying jenkins version 2.222.3), on the second run of the role, I get the "A later version is already installed" error, because this role actually upgrades from 2.222.3 to 2.270 (Debian Buster's latest I presume?).

The target machine's `/var/log/apt/history.log` shows only one item containing "jenkins":

```
Start-Date: 2020-12-14  20:51:58
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install jenkins
Requested-By: ansible (1000)
**Upgrade: jenkins:amd64 (2.222.3, 2.270)**
End-Date: 2020-12-14  20:52:01
```
 
and `/var/log/apt/term.log` shows this at the same time:

```
Preparing to unpack .../archives/jenkins_2.270_all.deb ...
Unpacking jenkins (2.270) over (2.222.3) ...
Setting up jenkins (2.270) ...
```

So, it definitely appears that this role is upgrading the jenkins package installed on Debian machines on subsequent runs. I'm not yet sure why this is happening. The [ansible apt module docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html) indicate that it doesn't upgrade by default. I'm flummoxed, but this appears to be a Debian-ism I don't yet understand.

**Comment by timblaktu** [comment]
This problem appears to be fix-able by adding `force: yes` in the `apt:` task that installs the downloaded .deb. I will submit a PR for this to hopefully raise more awareness..
