### ISSUE TITLE
Create + chown custom `jenkins_home`?

### ISSUE THREAD

**Issue by ringods** [geerlingguy/ansible-role-jenkins#220]
This role has the ability to set a custom `jenkins_home` path. But should this role also be responsible to create that path, and `chown` it to the `jenkins` user?

I tried this role in my playbook but the Jenkins boot failed because the path didn't exist.

**Comment by MisterTerrific** [comment]
I've run into this issue as well & it does appear that this role supports creating the directory.

e.g. https://github.com/geerlingguy/ansible-role-jenkins/blob/master/tasks/settings.yml#L43-L50

However the problem is that it needs to be executed before line 23, (https://github.com/geerlingguy/ansible-role-jenkins/blob/master/tasks/settings.yml#L23). I tested this theory out and it worked as expected from there.

@geerlingguy This is a small change, would you please be able to update the settings.yml to accommodate this request? (Otherwise I can create a pull request for this.)
