### ISSUE TITLE
HTTPS support for Jenkins

### ISSUE THREAD

**Issue by EdwardPrentice** [geerlingguy/ansible-role-jenkins#273]
Hello @geerlingguy 

I would like to raise this as a question really which I think would benefit those thinking about making PRs and contributing to make this role more https friendly.

You've mentioned you use this role with an nginx role to provide an https front door. Would you mind explaining the rationale for that? What is the advantage to using Nginx?

Given that Jenkins does in fact support https natively, is it reasonable that this role also supports https and its various configuration options?

I'm happy to contribute towards a PR with configuration options for https but it seems like perhaps you've deliberately chosen not to support it - so just want to clarify your current stance and what a good PR might look like in your mind.

Equally, I'm interested in looking for a playbook where you are using this role, the certbot role and the nginx role to build an https Jenkins instance - if there's such an example somewhere?

Thanks.

**Comment by EdwardPrentice** [comment]
😭

**Comment by geerlingguy** [comment]
Here's an example using Nginx as an https proxy: https://github.com/geerlingguy/ansible-for-devops/tree/master/https-nginx-proxy

And here's one using let's encrypt: https://github.com/geerlingguy/ansible-for-devops/tree/master/https-letsencrypt

I have my own Jenkins servers set up using certbot + nginx in front of Jenkins, but unfortunately can't share those Jenkins project repos :(

If the changes to this role to make Jenkins _natively_ support HTTPS are relatively simple, I might be willing to merge them. However, I have found java-based applications and HTTPS to not usually be that simple, which is why it's easier for me to just use http and proxy them via nginx or ingress or whatever other method is more standard.

Note that the [Jenkins HTTPS documentation](https://wiki.jenkins.io/pages/viewpage.action?pageId=135468777) even recommends using a proxy, at the top of that page, rather than use native HTTPS...

**Comment by EdwardPrentice** [comment]
I wonder why the Jenkins documentation recommends a proxy. I'll adopt your certbot+nginx+jenkins approach. Thanks Jeff ⭐️

**Comment by timblaktu** [comment]
@EdwardPrentice it recommends using a proxy, OR using iptables to port forward 443 to 8443 in the same breath. I am using the iptables approach, and after having automated the copying and conversion of the ssl certs/keys, I am now at the point of needing to change the following in the jenkins config file (/etc/default/jenkins as I am on Debian):

```
#disable HTTP
JENKINS_PORT="-1"

#configure HTTPS
JENKINS_HTTPS_PORT="8443"
JENKINS_HTTPS_KEYSTORE="/etc/jenkins/jenkins_keystore.jks"
JENKINS_HTTPS_KEYSTORE_PASSWORD="blahblahblah"
JENKINS_HTTPS_LISTEN_ADDRESS="127.0.0.1"

```

and aside from the JENKINS_PORT (which can be set through role variable `jenkins_http_port`), there is no support in this role for setting the other JENKINS_HTTPS_* config variables.

@geerlingguy is there anyway with your role to add arbitrary lines to the jenkins service config file, or should I just use lineinfile? Would you be amenable to adding support for setting these variables through your role? I have a fork and could submit a PR for this if I thought it might be accepted.
