### ISSUE TITLE
Several tasks fail in check mode when the role has not yet run succesfully

### ISSUE THREAD

**Issue by m8ram** [geerlingguy/ansible-role-jenkins#338]
E.g. in `tasks/main.yml` the task `Wait for Jenkins to start up before proceeding.` will fail after all of the retries unless the `setup-<family>` tasks have actually completed successfully.

The task currently has `check_mode: false` This forces a task to run in normal mode and make changes to the system, even when the playbook is called with `--check`.
I don't believe this is what is wanted here.
Instead I believe this task should be skipped in check mode (`when: not ansible_check_mode`)

The same applies to:
-  'Get the jenkins-cli jarfile from the Jenkins server.' in `tasks/main.yml`
- 'Download current plugin updates from Jenkins update site.' in `tasks/plugin.yml`
- 'Remove first and last line from json file.' in `tasks/plugin.yml`
- 'Install Jenkins plugins using password.' in `tasks/plugin.yml`

The last task already has a `when` condition. I believe the condition should be extended to:
```
when: ( jenkins_admin_password | default(false) ) and ( not ansible_check_mode )
```

**Comment by bertvv** [comment]
This is impossible to fix. Often, executing a task will make sure that a certain precondition of a later task is met. E.g. you first download/copy a file and then make changes to the permissions. In --check mode, the latter task will fail, since the file wasn't downloaded by the former. This is a general Ansible issue, not specific to this role.
