### ISSUE TITLE
Avoid 2.0 setup wizard but provide secure-by-default configuration

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-jenkins#50]
Jenkins < 2.0 was insecure-by-default.

Jenkins 2.0 introduced a mandatory setup wizard that makes the installation secure-by-default.

But for CD/CI of Jenkins _itself_ (via Ansible or other tools), you need to pass the `-Djenkins.install.runSetupWizard=false` option in either global `JAVA_OPTS` or in `JENKINS_JAVA_OPTIONS` in the Jenkins init file. Due to reasons stated in #47, though, using that option is not consistent/easy in all OS environments (e.g. Debian/Ubuntu)... and it also (if just using that option) makes the Jenkins installation insecure-by-default.

I'd like to skip the setup wizard yet still provide a secured installation, and also make sure the 2.0 install works the same across Ubuntu 12/14/16 and CentOS 6/7.

I'd also like to get the CLI plugin installation working again, but that could be broken out into a separate issue.

See related discussions/posts:

  - https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+CLI
  - https://groups.google.com/forum/#!topic/jenkinsci-users/Pb4QZVc2-f0
  - https://issues.jenkins-ci.org/browse/JENKINS-34035

**Comment by geerlingguy** [comment]
See especially https://groups.google.com/d/msg/jenkinsci-users/Pb4QZVc2-f0/ywKqZVf9MgAJ — could we do the following two steps to work around the issue and provide a secure (and customized) password for the default admin account?

  1. Create the file `/var/lib/jenkins/jenkins.install.UpgradeWizard.state` with one line, `2.0`
  2. Create the file `/var/lib/jenkins/init.groovy.d/basic-security.groovy` with the contents:

```
#!groovy

import jenkins.model.*
import hudson.security.*

def instance = Jenkins.getInstance()

println "--> creating local user 'admin'"

def hudsonRealm = new HudsonPrivateSecurityRealm(false)
hudsonRealm.createAccount('admin','admin')
instance.setSecurityRealm(hudsonRealm)

def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
instance.setAuthorizationStrategy(strategy)
instance.save()
```

**Comment by stuart-warren** [comment]
s/Ansible/Jenkins/2

Pretty sure that's all I'm doing, other than the fact I tend to use a different script setting up LDAP auth instead. Only takes effect on the next start of Jenkins, so likely needs to be restarted after the package install autostarts the service.

I'm not using the CLI jar at all though, so you might have fun with authentication there.

**Comment by geerlingguy** [comment]
@stuart-warren - Oops, thanks! And yeah, the CLI jar is where I'm hitting the most difficulty. Will take a look at votum's role.

**Comment by geerlingguy** [comment]
See also:

> @geerlingguy Jeff: I took a lot of inspiration from your role here when I built out my [ansible-jenkins2](https://github.com/karlmdavis/ansible-jenkins2) variant, so just thought I'd point you at my solution for the security challenges you were running into here.
> 
> I use an [init.d/adminSshKeys.groovy script](https://github.com/karlmdavis/ansible-jenkins2/blob/master/templates/adminSshKeys.groovy) to solve the security challenges you were running into here (and perhaps the other two init scripts I use also help a bit-- can't quite remember).
> 
> Feel free to steal "inspiration", yourself! Huzzah for open source!

From @karlmdavis, in [this comment](https://github.com/geerlingguy/ansible-role-jenkins/issues/47#issuecomment-216521995).

**Comment by oloc** [comment]
The Jenkins version is not always 2.0. So, may I suggest to avoid the setup wizard : 
```
  - name: Bypass - jenkins.install.InstallUtil.lastExecVersion
    copy: src={{ jenkins_home }}/jenkins.install.UpgradeWizard.state
          dest={{ jenkins_home }}/jenkins.install.InstallUtil.lastExecVersion
          owner={{ jenkins_user }}
          group={{ jenkins_user }}
          remote_src=True

  - stat: path={{ jenkins_home }}/secrets/initialAdminPassword
    register: adminpassword

  - name: Bypass - initialAdminPassword
    shell: mv {{ jenkins_home }}/secrets/initialAdminPassword /root
    notify:
      - restart jenkins
    when: adminpassword.stat.exists == True
```
For sure, defaults/main.yml contains: 
```
jenkins_user: "jenkins"
jenkins_home: "/var/lib/jenkins"
```

**Comment by noidi** [comment]
For what it's worth, I've added Jenkins 2 support to [solita.jenkins](https://github.com/solita/ansible-role-solita.jenkins), which builds on top of this role. Here are the key pieces of the solution (many of which are taken from the issues and pull requests to this role, thanks everyone):

1. [Disable the setup wizard](https://github.com/solita/ansible-role-solita.jenkins/blob/master/tasks/security.yml#L31-L38).
2. [Place a script in `init.groovy.d`](https://github.com/solita/ansible-role-solita.jenkins/blob/master/tasks/security.yml#L40-L48) to [configure the security realm](https://github.com/solita/ansible-role-solita.jenkins/blob/master/templates/solita_jenkins_security_realm.groovy.j2#L10-L15). (I install the `matrix-auth` plugin and use `GlobalMatrixAuthorizationStrategy`, but `FullControlOnceLoggedInAuthorizationStrategy` could work as well, if you're OK with allowing anonymous read access to the instance.)
3. [Create an SSH key for the unix user](https://github.com/solita/ansible-role-solita.jenkins/blob/master/tasks/security.yml#L2-L7) and [add it to the admin user](https://github.com/solita/ansible-role-solita.jenkins/blob/master/templates/solita_jenkins_security_realm.groovy.j2#L17-L19). This way the CLI knows how to map the unix user to a Jenkins user. (I create a new Jenkins user for my role, but I think using the `admin` user that Jenkins 2 has by default could work as well. I'm not sure if `admin` is created when upgrading from Jenkins 1, though.)
4. [Set the JNLP port](https://github.com/solita/ansible-role-solita.jenkins/blob/master/tasks/security.yml#L50-L57) so the CLI can connect to the server.
5. [Change Jenkins' settings](https://github.com/solita/ansible-role-solita.jenkins/blob/master/tasks/jenkins_23232.yml) to work around [JENKINS-23232](https://issues.jenkins-ci.org/browse/JENKINS-23232). Without this fix the CLI didn't work on my test machines.
6. [Don't install plugins until all of the above has been done and Jenkins has been restarted.](https://github.com/solita/ansible-role-solita.jenkins/blob/master/tasks/main.yml#L2-L7)

If you want to give `solita.jenkins` a try, it comes with a `Vagrantfile` (in the `test` directory). It sets up port forwarding so that you can access the Jenkins installation from your host at [http://localhost:9080/jenkins](http://localhost:9080/jenkins).

I hope this "reference implementation" can be of some help with fixing this issue.

/cc @geerlingguy

**Comment by geerlingguy** [comment]
I'm going to shoot for the minimal working approach here—and in the meantime, this will make the role only work on new installations if you're using Jenkins 2.x. I'd be willing to consider making the role support fresh 1.x installs as well if someone wants to do the time, but I'll be bumping the major version of this role to mark the change to 2.x-centric development, and we can go from there. Latest work (which also seems to work okay with plugin install) is at #65

**Comment by davidkarim** [comment]
greelingguy, thanks a lot for the groovy script. Just wanted to point out that using the setAllowAnonymousRead method allows you to disable read-only access for anonymous users. Thought this might be useful to some; here is the modification (tested it on Jenkins 2.21):

```
#!groovy

import jenkins.model.*
import hudson.security.*

def instance = Jenkins.getInstance()

println "--> creating local user 'admin'"

def hudsonRealm = new HudsonPrivateSecurityRealm(false)
hudsonRealm.createAccount('{{ jenkins_admin_username }}','{{ jenkins_admin_password }}')
instance.setSecurityRealm(hudsonRealm)

def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
strategy.setAllowAnonymousRead(false)
instance.setAuthorizationStrategy(strategy)
instance.save()
```
