### ISSUE TITLE
Please make it compatible with systemd

### ISSUE THREAD

**Issue by deimosfr** [geerlingguy/ansible-role-jenkins#8]
Hi,

The current role is not compatible with systemd. You can find more information here:

https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+as+a+Unix+daemon

Thanks in advance

**Comment by deimosfr** [comment]
If you pickup the systemd configuration from Debian jessie, it works like a charm. You just need to add this content in a /etc/init/jenkins.conf file:
```
description "Jenkins Continuous Integration Server"
author "James Page <james.page@ubuntu.com>"

start on runlevel [2345]
stop on runlevel [!2345]

limit nofile 8192 8192

pre-start script
    [ -r /etc/default/jenkins ] && . /etc/default/jenkins
    test -f $JENKINS_WAR || { stop ; exit 0; }
    $JENKINS_ROOT/bin/maintain-plugins.sh 	
    mkdir $JENKINS_RUN > /dev/null 2>&1  || true
    chown -R $JENKINS_USER $JENKINS_RUN || true 
end script

script
    [ -r /etc/default/jenkins ] && . /etc/default/jenkins
    export JENKINS_HOME
    exec start-stop-daemon --start -c $JENKINS_USER --exec $JAVA --name jenkins \
        -- $JAVA_ARGS -jar $JENKINS_WAR $JENKINS_ARGS --logfile=$JENKINS_LOG
end script
```
And it works :-). I hope you'll integrate it soon.

Thanks

**Comment by deimosfr** [comment]
Hi, any news ?

**Comment by geerlingguy** [comment]
Not yet... Do you know if there is any way we can use what's installed with the jenkins apt repo instead of relying on a self-supplied script for this functionality? I'd hate to have to maintain the startup/deamonize script in case it needs tweaking over time.

**Comment by deimosfr** [comment]
Well in fact, if you're taking the version provided by Debian Jessie, it's this script which is used for systemd. However I can't tell when it will be integrated in the official repository. As next version of Ubuntu and Debian will be released with Systemd, there will be a problem if nothing is made.

I strongly suggest that you add this in the role in waiting of a real integration in the official repository.

**Comment by deimosfr** [comment]
Hi,

Any news ?

**Comment by geerlingguy** [comment]
@deimosfr - I'll hopefully get around to this soon; if someone can work on a PR to make sure this works with whatever versions of Debian/Ubuntu require it, I'd be willing to review/accept that work. Otherwise this is a little lower priority for me right now, as I don't run any active infrastructure that integrates Jenkins with `systemd`.

**Comment by geerlingguy** [comment]
For now I'm going to close this out; the role/official repos work fine with all the supported flavors of Linux for this role (RHEL/CentOS 6/7 and Ubuntu 12/14... and Debian 7 at least (I haven't done full testing/support for 8 yet)).

I'd rather leave the actual init scripts and that configuration up to the official Jenkins repos, rather than maintain it separately in this role—at least for the foreseeable future.
